#!/bin/sh

toolDirectory=$(dirname $(dirname $0))
revision=$(basename $(realpath ${toolDirectory}))
userDirectory=$HOME/DFTman/${revision}

if [ ! -d $HOME/notebooks/DFTman ]; then
    mkdir -p $userDirectory
    ln -s $toolDirectory/launcher.ipynb $userDirectory/launcher.ipynb
    ln -s $toolDirectory/launcher.py $userDirectory/launcher.py
    cp -r $toolDirectory/projects $userDirectory/projects
    cp $toolDirectory/projects.json $userDirectory/projects.json
    mkdir $userDirectory/bin
    cp $toolDirectory/bin/default.ipynb $userDirectory/bin/default.ipynb
fi

/usr/bin/invoke_app "$@" -C "start_jupyter -t $userDirectory/launcher.ipynb" \
                         -u anaconda3-5.1

