#!/bin/sh

if [ ! -d $HOME/notebooks/DFTman ]; then
    mkdir -p $HOME/notebooks/DFTman
    ln -s /apps/dftman/dev/launcher.ipynb $HOME/notebooks/DFTman/launcher.ipynb
    ln -s /apps/dftman/dev/launcher.py $HOME/notebooks/DFTman/launcher.py
    cp -r /apps/dftman/dev/projects.json $HOME/notebooks/DFTman/projects.json
    cp -r /apps/dftman/dev/projects $HOME/notebooks/DFTman/projects
    mkdir $HOME/notebooks/DFTman/bin
    cp /apps/dftman/dev/bin/default.ipynb $HOME/notebooks/DFTman/bin/default.ipynb
fi

/usr/bin/invoke_app "$@" -C "start_jupyter -t $HOME/notebooks/DFTman/launcher.ipynb" \
                         -u anaconda3-5.1
